{% set name = "osmium" %}
{% set version = "3.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c7b4becb5f13aa82421b269e583bee4d14b56a2c490b334d44ec954cb480a289

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - lz4-c
    - pip
  host:
    - python >=3.6
    - expat
    - zlib
    - bzip2
    - boost
    - lz4-c
  run:
    - python >=3.6
    - requests
    - expat
    - zlib
    - bzip2
    - boost

test:
  imports:
    - osmium
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://osmcode.org/pyosmium/
  summary: Python bindings for libosmium, the data processing library for OSM data
  license: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - brynpickering
