{% set name = "xml2" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/mnhrdt/xml2.git

build:
  script: make "xml2" "2csv" && mkdir -p $PREFIX/bin && cp "xml2" "2csv" $PREFIX/bin  # [not win]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - make
    - libxml2
  host:
    - libxml2
  run:
    - libxml2

test:
  files:
    - sample.xml
    - sample.csv
  commands:
    - xml2 < sample.xml | 2csv events/event @time @type @link @vehicle > output.csv
    - diff output.csv sample.csv  # [not win]

about:
  home: https://github.com/byrnpickering/xml2
  summary: XML to CSV scripts
  license: GPLv2
  license_file: LICENSE

extra:
  recipe-maintainers:
    - brynpickering