name: Build Package

on:
  push:

jobs:
  find-out-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-output.outputs.matrix }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v39
      with:
        dir_names: true
        dir_names_max_depth: 1
        json: false
        quotepath: false
        files: "**/meta.yaml"
        files_ignore: .github/**/*

    - name: 'Set output in the matrix format'
      id: set-output
      if: steps.changed-files.outputs.all_changed_files != ''
      run: |
        STR=""
        echo ${{ steps.changed-files.outputs.all_changed_files }}
        for FILE in ${{ steps.changed-files.outputs.all_changed_files }}
        do
          echo $FILE
          VERSION=$(grep -o 'version = \"[a-zA-Z0-9\.]*\"' $FILE/meta.yaml | cut -d \" -f 2)
          STR+="{\"dir\":\"$FILE\", \"version\":\"v$VERSION\"},"
          echo $STR
        done
        MATRIX="{\"include\": [${STR%?}]}"
        echo $MATRIX
        echo "matrix=$MATRIX" >> $GITHUB_OUTPUT


  conda-build-noarch:
    needs: [find-out-changes]
    if: needs.find-out-changes.outputs.matrix != ''
    strategy: ${{ fromJson(needs.find-out-changes.outputs.matrix) }}
    uses: arup-group/actions-city-modelling-lab/.github/workflows/conda-build.yml@add-conda-build-args
    secrets:
      ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
    with:
      package_name: ${{ matrix.dir }}
      recipe_dir: ${{ matrix.dir }}
      version: ${{ matrix.version }}
